# Use the official Node.js image from the Docker Hub
FROM node:latest

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the default port for the application
EXPOSE 3000

# Start the application
CMD ["npm", "start"]

# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=pgappd_local
ENV POSTGRES_USER=postgres

# Use Docker secrets for the PostgreSQL password
ENV POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password

# Copy initialization scripts
COPY init-db.sh /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432

#Build: docker-compose -f docker-compose_adamaurelio.yml up --build
#Tear Down:  docker-compose -f docker-compose_adamaurelio.yml down